# Generated by Django 5.2.9 on 2026-05-22 20:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0002_userdevice_userprofile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MarketingCampaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=200, null=True)),
                ('content', models.TextField(help_text='Markdown or plain text description')),
                ('image_url', models.URLField(blank=True, max_length=500, null=True)),
                ('cta_text', models.CharField(default='Explore', max_length=50)),
                ('cta_link', models.CharField(default='/', max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('target_filter', models.CharField(choices=[('ALL', 'All Users'), ('NO_INVESTMENTS', 'No Investments'), ('DEBTORS', 'Debtors (Has Loans/Debts)')], default='ALL', max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('message', models.TextField()),
                ('notification_type', models.CharField(choices=[('BUDGET_ALERT', 'Budget Alert'), ('INFO', 'Info'), ('SYSTEM', 'System')], default='INFO', max_length=20)),
                ('is_read', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('threshold', models.IntegerField(blank=True, null=True)),
                ('alert_month', models.DateField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='finances.category')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
