# Generated by Django 5.2.9 on 2026-05-23 09:35

from django.db import migrations, models
import django.core.validators


class Migration(migrations.Migration):

    dependencies = [
        ('finances', '0004_budget_is_deleted_notification_is_deleted_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='marketingcampaign',
            name='image_url',
        ),
        migrations.AddField(
            model_name='marketingcampaign',
            name='image',
            field=models.ImageField(
                blank=True,
                help_text='Upload campaign banner image (JPG, JPEG, PNG, AVIF supported)',
                null=True,
                upload_to='campaigns/',
                validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png', 'avif'])]
            ),
        ),
    ]
