# Generated by Django 5.2.9 on 2025-12-08 21:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Debt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('person_name', models.CharField(help_text='Name of the person involved', max_length=100)),
                ('debt_type', models.CharField(choices=[('GIVEN', 'I gave money (Asset)'), ('TAKEN', 'I borrowed money (Liability)')], max_length=10)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('description', models.TextField(blank=True, help_text='Reason for lending/borrowing', null=True)),
                ('transaction_date', models.DateField(default=datetime.date.today)),
                ('due_date', models.DateField(blank=True, help_text='When is it expected back?', null=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PARTIAL', 'Partially Paid'), ('SETTLED', 'Settled / Paid')], default='PENDING', max_length=10)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='debts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Loan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. HDFC Home Loan', max_length=100)),
                ('loan_type', models.CharField(choices=[('HOME', 'Home Loan'), ('CAR', 'Car Loan'), ('PERSONAL', 'Personal Loan'), ('EDUCATION', 'Education Loan'), ('OTHER', 'Other')], default='PERSONAL', max_length=20)),
                ('total_principal', models.DecimalField(decimal_places=2, help_text='Total amount borrowed', max_digits=12)),
                ('interest_rate', models.DecimalField(decimal_places=2, help_text='Annual Interest Rate in %', max_digits=5)),
                ('start_date', models.DateField()),
                ('tenure_months', models.PositiveIntegerField(help_text='Total duration in months')),
                ('emi_amount', models.DecimalField(decimal_places=2, help_text='Monthly EMI cost', max_digits=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loans', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
