# Generated by Django 5.2.9 on 2026-05-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('obligations', '0002_emipayment'),
    ]

    operations = [
        migrations.AddField(
            model_name='debt',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='emipayment',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='loan',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
