# Generated by Django 5.2.9 on 2025-12-11 11:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Asset',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='e.g. Tata Motors', max_length=100)),
                ('symbol', models.CharField(help_text='e.g. TATAMOTORS.NS or 112093 (MF Code)', max_length=50)),
                ('asset_type', models.CharField(choices=[('STOCK', 'Stock / Share'), ('MF', 'Mutual Fund'), ('GOLD', 'Digital Gold / SGB'), ('CRYPTO', 'Cryptocurrency')], default='STOCK', max_length=10)),
                ('quantity', models.DecimalField(decimal_places=4, help_text='Number of units/shares', max_digits=10)),
                ('buy_price_avg', models.DecimalField(decimal_places=2, help_text='Average buying price per unit', max_digits=12)),
                ('current_market_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assets', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
