# Generated by Django 5.2.9 on 2026-05-23 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='asset',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
    ]
